GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/usuarios/2

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "prueba@uv.mx",
    "password": "patito",
    "nombre": "Un nuevo usuario pato",
    "rol": "Administrador"
}

###

PUT http://localhost:3000/api/usuarios/prueba@uv.mx
Content-Type: application/json

{
    "id": 3,
    "nombre": "Usuario pato editado",
    "rol": "Usuario"
}

###

DELETE http://localhost:3000/api/usuarios/gvera@localhost:3000/api/usuarios/gvera@uv.mx

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmRlZmluZWQiOiJndmVyYUB1di5teCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Ikd1aWxsZXJtbyBWZXJhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QiLCJpYXQiOjE3MTU4MzUwNzYsImV4cCI6MTcxNTgzNjI3Nn0.kJiBKctKrnZQsE-kqrK5dY_7CaWfhoMoizycMOxuhHA

{
    "email": "prueba2@uv.mx",
    "password": "patito2",
    "nombre": "Un nuevo usuario pato2",
    "rol": "Administrador"
}

###